import pg from 'pg';
import { randomUUID } from 'node:crypto';
const { Pool } = pg;
const DATABASE_URL=process.env.DATABASE_URL;
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,ssl:process.env.PGSSLMODE==='disable'?false:{rejectUnauthorized:false}}):null;
function requirePool(){if(!pool)throw new Error('DATABASE_URL is not configured.');return pool;}
function safeTable(table){if(!/^[A-Za-z0-9_]+$/.test(table))throw new Error('Invalid database table name.');return `"${table}"`;}
async function ensureTable(table){await requirePool().query(`CREATE TABLE IF NOT EXISTS ${safeTable(table)} (id uuid PRIMARY KEY, record jsonb NOT NULL)`);}
function decodeToken(token){if(!token)return 0;try{return Math.max(0,Number(Buffer.from(token,'base64url').toString('utf8'))||0)}catch{return 0}}
function encodeToken(offset){return Buffer.from(String(offset),'utf8').toString('base64url')}
export const db={async add(table,records){await ensureTable(table);const c=requirePool(),out=[];for(const record of records){try{const id=randomUUID();const r=await c.query(`INSERT INTO ${safeTable(table)} (id, record) VALUES ($1,$2::jsonb) RETURNING id`,[id,JSON.stringify(record)]);out.push(r.rows[0]?.id??null)}catch{out.push(null)}}return out},async update(table,items){await ensureTable(table);const c=requirePool(),out=[];for(const item of items){try{const r=await c.query(`UPDATE ${safeTable(table)} SET record=$1::jsonb WHERE id=$2`,[JSON.stringify(item.record),item.id]);out.push(r.rowCount===1)}catch{out.push(false)}}return out},async get(table,ids){await ensureTable(table);if(!ids.length)return[];const r=await requirePool().query(`SELECT id,record FROM ${safeTable(table)} WHERE id=ANY($1::uuid[])`,[ids]);const m=new Map(r.rows.map(x=>[String(x.id),x.record]));return ids.map(id=>m.has(id)?m.get(id):null)},async list(table,options={}){await ensureTable(table);const limit=Math.min(1000,Math.max(1,Number(options.limit||50))),offset=decodeToken(options.nextToken);const r=await requirePool().query(`SELECT id,record FROM ${safeTable(table)} ORDER BY id LIMIT $1 OFFSET $2`,[limit,offset]);const items=r.rows.map(x=>({...x.record,id:String(x.id)}));return{items,...(r.rows.length===limit?{nextToken:encodeToken(offset+r.rows.length)}:{})}},async delete(table,ids){await ensureTable(table);if(!ids.length)return[];const r=await requirePool().query(`DELETE FROM ${safeTable(table)} WHERE id=ANY($1::uuid[]) RETURNING id`,[ids]);const d=new Set(r.rows.map(x=>String(x.id)));return ids.map(id=>d.has(id))}};
export const secrets={async readSecret(name){const value=process.env[name];if(!value)throw new Error(`Secret ${name} is not configured.`);return value},async listSecretNames(){return Object.keys(process.env).filter(n=>n.endsWith('_API_KEY')||n==='BAZAARLINK_API_KEY')}};
export function json(data,status=200){return{statusCode:status,headers:{'Content-Type':'application/json; charset=utf-8'},body:JSON.stringify(data)}}
export function error(message,status=400){return json({error:message},status)}
function compileRoute(pattern){const names=[];const source=pattern.split('/').map(part=>{if(part.startsWith(':')){names.push(part.slice(1));return'([^/]+)'}return part.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}).join('/');return{regex:new RegExp(`^${source}/?$`),names}}
export function router(routes){const compiled=Object.entries(routes).map(([key,middleware])=>{const i=key.indexOf(' ');return{method:key.slice(0,i).toUpperCase(),...compileRoute(key.slice(i+1)),middleware}});return async event=>{const method=String(event?.httpMethod||event?.requestContext?.http?.method||'GET').toUpperCase(),rawPath=String(event?.path||event?.rawPath||event?.requestContext?.http?.path||'/'),url=new URL(rawPath,'http://sire.local'),query=Object.fromEntries(url.searchParams.entries());let body=event?.body;if(typeof body==='string'&&body)try{body=JSON.parse(body)}catch{}if(body==null)body={};for(const route of compiled){if(route.method!==method)continue;const match=url.pathname.match(route.regex);if(!match)continue;const params={};route.names.forEach((name,index)=>params[name]=decodeURIComponent(match[index+1]));let response;try{for(const fn of route.middleware){response=await fn({body,query,params,event});if(response)break}return response||json({ok:true})}catch(cause){return error(cause instanceof Error?cause.message:String(cause),500)}}return error('Not found',404)}}
const websocketClients=new Map();
export const ws={register(id,socket){websocketClients.set(id,socket)},unregister(id){websocketClients.delete(id)},async send(ids,payload){const text=JSON.stringify(payload);for(const id of ids){const socket=websocketClients.get(id);if(socket&&socket.readyState===1)socket.send(text)}}};
