import { useEffect, useState } from 'react';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import { WalletKitBridge } from './reownWallet';
import { SireErrorBoundary, SireErrorScreen, getSireErrorMessage } from './SireErrorBoundary';
import './index.css';
import './home-value-panel.css';
import './mobile.css';
import './tabNavigation';
import './navigationAutoHide';
import './tabLayoutController';
import './quoteLogoHeader';
import './quoteLogoPositionFix';