const STYLE_ID = 'sire-tab-navigation-style';
const NAV_ID = 'sire-bottom-tabs';
const BAR_ID = 'sire-chart-bottom-bar';
const FLOAT_ID = 'sire-chart-floating-quote';
type Tab = 'sire' | 'chart' | 'quote';
function injectStyles() {
  if (document.getElementById(STYLE_ID)) return;
  const style = document.createElement('style'); style.id = STYLE_ID;
  style.textContent = `
    .sire-tab-mode .symbol-sidebar{display:none!important}.sire-tab-mode .chart-terminal{width:100%!important}
    .sire-tab-mode .terminal-topbar{display:none!important}.sire-tab-mode .terminal-topbar .instrument-picker,.sire-tab-mode .terminal-topbar .live-state,.sire-tab-mode .chart-subbar,.sire-tab-mode .research-controls,.sire-tab-mode button[title="Open GPT research laboratory"]{display:none!important}
    .sire-tab-quote .terminal-body{display:block!important;padding-bottom:108px!important}.sire-tab-quote .chart-terminal{display:none!important}.sire-tab-quote .symbol-sidebar{display:flex!important;width:100%!important;height:calc(100vh - 132px)!important;border-right:0!important;padding:16px 16px 108px!important;box-sizing:border-box}.sire-tab-quote .sidebar-search{max-width:760px;width:100%;margin:0 auto 12px}.sire-tab-quote .sidebar-meta{max-width:760px;width:100%;margin:0 auto 10px}.sire-tab-quote .symbol-list{width:100%;max-width:760px;margin:0 auto;display:grid!important;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px;overflow-y:auto;align-content:start;padding-bottom:8px}.sire-tab-quote .symbol-row{min-height:82px;padding:14px!important;border:1px solid rgba(255,255,255,.08);border-radius:14px;background:rgba(255,255,255,.025);text-align:left}.sire-tab-quote .symbol-row.active{border-color:rgba(255,255,255,.72);background:rgba(255,255,255,.07);box-shadow:0 0 18px rgba(255,255,255,.08)}.sire-tab-quote .catalogue-refresh{width:min(760px,100%);margin:12px auto 0}
    .sire-chat-only-header .sire-chat-context,.sire-chat-only-header .sire-chat-only-close{display:none!important}.sire-chat-only-composer{bottom:62px!important;transition:transform .22s ease,opacity .22s ease}.sire-chat-only-composer.is-scroll-hidden{transform:translateY(calc(100% + 22px))!important;opacity:0!important;pointer-events:none!important}
    #${FLOAT_ID}{position:fixed;z-index:9000;top:14px;left:14px;display:none;pointer-events:none;color:#fff;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;text-align:left;line-height:1.05;text-shadow:0 2px 10px rgba(0,0,0,.9)}#${FLOAT_ID}.show{display:block}#${FLOAT_ID} .float-name{font-size:14px;font-weight:700;letter-spacing:.02em;color:rgba(255,255,255,.94);margin-bottom:6px}#${FLOAT_ID} .float-price-row{display:flex;align-items:baseline;gap:9px;white-space:nowrap}#${FLOAT_ID} .float-price{font-size:22px;font-weight:700;letter-spacing:.01em;color:#fff}#${FLOAT_ID} .float-change{font-size:12px;font-weight:700;letter-spacing:.01em;color:rgba(255,255,255,.62)}#${FLOAT_ID} .float-change.up{color:#4fd1c5}#${FLOAT_ID} .float-change.down{color:#ff5b63}
    #${BAR_ID}{position:fixed;z-index:9001;left:50%;right:auto;bottom:calc(max(6px,env(safe-area-inset-bottom)) + 54px);transform:translateX(-50%);display:flex;align-items:center;width:min(720px,calc(100vw - 28px));height:56px;box-sizing:border-box;padding:6px 8px;margin:0;overflow-x:auto;overflow-y:hidden;white-space:nowrap;pointer-events:none;background:rgba(20,22,28,.30);border:1px solid rgba(255,255,255,.28);border-radius:22px;-webkit-backdrop-filter:blur(20px) saturate(125%);backdrop-filter:blur(20px) saturate(125%);box-shadow:0 10px 32px rgba(0,0,0,.28),inset 0 0 0 1px rgba(255,255,255,.045),0 0 20px rgba(255,255,255,.045);scrollbar-width:none;-webkit-overflow-scrolling:touch;touch-action:pan-x}#${BAR_ID}::-webkit-scrollbar{display:none}
    #${NAV_ID}{position:fixed;z-index:9999;left:50%;right:auto;bottom:max(6px,env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;align-items:center;justify-content:center;gap:10px;padding:0;margin:0;pointer-events:none;background:transparent;border:0}#${NAV_ID} button{pointer-events:auto;min-width:86px;height:46px;padding:0 17px;border:1px solid rgba(255,255,255,.32);border-radius:999px;background:rgba(20,22,28,.34);color:rgba(255,255,255,.72);-webkit-backdrop-filter:blur(18px) saturate(125%);backdrop-filter:blur(18px) saturate(125%);box-shadow:0 7px 22px rgba(0,0,0,.22),inset 0 0 0 1px rgba(255,255,255,.035),0 0 12px rgba(255,255,255,.035);font:700 11px/1 system-ui,sans-serif;letter-spacing:.09em;display:inline-flex;align-items:center;justify-content:center;gap:7px;cursor:pointer;touch-action:manipulation;-webkit-tap-highlight-color:transparent}#${NAV_ID} button.active{color:#fff;border-color:rgba(255,255,255,.9);background:rgba(255,255,255,.08);box-shadow:0 8px 26px rgba(0,0,0,.24),inset 0 0 0 1px rgba(255,255,255,.08),0 0 22px rgba(255,255,255,.18)}#${NAV_ID} .tab-icon{font-size:15px;line-height:1;opacity:.9}.sire-tab-mode .terminal-body{padding-bottom:82px!important}.sire-chat-only{padding-bottom:82px!important;box-sizing:border-box}
    @media(max-width:520px){
      html,body,#root{margin:0!important;padding:0!important;min-height:100%!important;background:#000!important}
      .sire-tab-mode.sire-chart-tab .terminal-shell,.sire-tab-mode.sire-chart-tab .terminal-body,.sire-tab-mode.sire-chart-tab .chart-terminal,.sire-tab-mode.sire-chart-tab .chart-stage{position:fixed!important;top:0!important;left:0!important;right:0!important;bottom:0!important;width:100%!important;height:100dvh!important;min-height:100dvh!important;margin:0!important;padding:0!important;box-sizing:border-box!important;transform:none!important}
      .sire-tab-mode.sire-chart-tab .terminal-shell{overflow:hidden!important;border:0!important;border-radius:0!important}
      .sire-tab-mode.sire-chart-tab .terminal-body{overflow:hidden!important}
      .sire-tab-mode.sire-chart-tab .chart-terminal,.sire-tab-mode.sire-chart-tab .chart-stage,.sire-tab-mode.sire-chart-tab .chart-area,.sire-tab-mode.sire-chart-tab .chart-container{background:#000!important}
      .sire-tab-mode.sire-chart-tab .chart-terminal{z-index:1!important}
      #${FLOAT_ID}{top:12px;left:14px}#${FLOAT_ID} .float-name{font-size:14px;margin-bottom:5px}#${FLOAT_ID} .float-price{font-size:21px}#${FLOAT_ID} .float-change{font-size:11px}
      #${BAR_ID}{bottom:calc(max(6px,env(safe-area-inset-bottom)) + 54px);width:calc(100vw - 28px);height:54px;border-radius:20px}
      #${NAV_ID}{gap:7px;bottom:max(6px,env(safe-area-inset-bottom));width:calc(100vw - 28px)}#${NAV_ID} button{flex:1 1 0;min-width:0;height:44px;padding:0 10px}.sire-chat-only-composer{bottom:60px!important}
    }
    @media(min-width:800px){#${BAR_ID}{bottom:64px}#${NAV_ID}{gap:12px}#${NAV_ID} button{min-width:94px;height:48px}}
  `; document.head.appendChild(style);
}
function findSireOpenButton(){return Array.from(document.querySelectorAll('button')).find(button=>button.getAttribute('title')==='Open GPT research laboratory') as HTMLButtonElement|undefined}
function findChatCloseButton(){return document.querySelector('.sire-chat-only-close') as HTMLButtonElement|null}
function wireChatComposer(){const messages=document.querySelector('.sire-chat-only-messages') as HTMLElement|null,composer=document.querySelector('.sire-chat-only-composer') as HTMLElement|null;if(!messages||!composer||composer.dataset.scrollWired==='true')return;composer.dataset.scrollWired='true';composer.classList.remove('is-scroll-hidden');let previousTop=messages.scrollTop;messages.addEventListener('scroll',()=>{const nextTop=messages.scrollTop,delta=nextTop-previousTop;if(Math.abs(delta)>=4){composer.classList.toggle('is-scroll-hidden',delta>0&&nextTop>12);previousTop=nextTop}},{passive:true})}
function ensureFloatingQuote(){let el=document.getElementById(FLOAT_ID);if(el)return el;el=document.createElement('div');el.id=FLOAT_ID;el.innerHTML='<div class="float-name"></div><div class="float-price-row"><span class="float-price"></span><span class="float-change"></span></div>';document.body.appendChild(el);return el}
function updateFloatingQuote(){const el=ensureFloatingQuote();const source=document.querySelector('.chart-subbar');if(!source)return;const main=source.children[0] as HTMLElement|null;const ohlc=source.children[1] as HTMLElement|null;const priceNode=main?.querySelector('i') as HTMLElement|null;const nameNode=main?.querySelector('b') as HTMLElement|null;if(!main||!priceNode||!nameNode)return;const name=nameNode.textContent?.trim()||'';const price=priceNode.textContent?.trim()||'—';const raw=ohlc?.textContent||'';const numbers=raw.match(/[0-9][0-9,]*(?:\.[0-9]+)?/g)||[];let change='';if(numbers.length>=4){const open=Number(numbers[0].replace(/,/g,''));const close=Number(numbers[3].replace(/,/g,''));if(Number.isFinite(open)&&open!==0&&Number.isFinite(close)){const pct=((close-open)/open)*100;change=`${pct>=0?'▲ +':'▼ '}${pct.toFixed(2)}%`;}}
el.querySelector('.float-name')!.textContent=name;el.querySelector('.float-price')!.textContent=price;const changeNode=el.querySelector('.float-change')!;changeNode.textContent=change;changeNode.classList.toggle('up',change.startsWith('▲'));changeNode.classList.toggle('down',change.startsWith('▼'));}
function setFloatingVisible(visible:boolean){ensureFloatingQuote().classList.toggle('show',visible)}
function wireFloatingQuote(){updateFloatingQuote()}
function setTab(tab:Tab){const root=document.getElementById('root'),nav=document.getElementById(NAV_ID);if(!root||!nav)return;root.classList.toggle('sire-tab-mode',tab!=='quote');root.classList.toggle('sire-tab-quote',tab==='quote');root.classList.toggle('sire-chart-tab',tab==='chart');setFloatingVisible(tab==='chart');const bar=document.getElementById(BAR_ID);if(bar)bar.style.display=tab==='chart'?'flex':'none';nav.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.tab===tab));if(tab==='sire'){findSireOpenButton()?.click();window.setTimeout(wireChatComposer,0)}else findChatCloseButton()?.click()}
function mountNavigation(){injectStyles();if(document.getElementById(NAV_ID))return;ensureFloatingQuote();wireFloatingQuote();const bar=document.createElement('div');bar.id=BAR_ID;bar.setAttribute('aria-label','Chart tools');bar.setAttribute('role','toolbar');document.body.appendChild(bar);const nav=document.createElement('nav');nav.id=NAV_ID;nav.setAttribute('aria-label','Primary navigation');const tabs:Array<[Tab,string,string]>=[['sire','✦','SIRE'],['chart','⌁','CHART'],['quote','▦','QUOTE']];tabs.forEach(([tab,icon,label])=>{const button=document.createElement('button');button.type='button';button.dataset.tab=tab;button.innerHTML=`<span class="tab-icon">${icon}</span><span>${label}</span>`;button.addEventListener('click',()=>setTab(tab));nav.appendChild(button)});document.body.appendChild(nav);setTab('chart')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mountNavigation,{once:true});else mountNavigation();
const observer=new MutationObserver(()=>{if(!document.getElementById(NAV_ID))mountNavigation();if(document.querySelector('.sire-chat-only-composer'))wireChatComposer()});observer.observe(document.documentElement,{childList:true,subtree:true});
setInterval(()=>{if(document.querySelector('.sire-chart-tab'))updateFloatingQuote()},1000);
